In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
# save array
np.save('myarray',arr)

In [5]:
# show if it was saved
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [7]:
# save another array
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# save both to a zip file
np.savez('ziparray.npz',x=arr1,y=arr2)
print('Zip file created')

Zip file created


In [13]:
archive_array = np.load('ziparray.npz')
print('Zip file loaded')

Zip file loaded


In [14]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Save and load text files
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.savetxt('mytextarray.txt',arr,delimiter=',')
print('File saved')

File saved


In [ ]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr