# CREATING ARRAYS

In [38]:
import numpy as np

In [39]:
my_list1 = [1,2,3,4]

In [40]:
my_array1 = np.array(my_list1)

In [41]:
my_array1

array([1, 2, 3, 4])

In [42]:
my_list2 = [11,22,33,44]

In [43]:
my_lists = [my_list1, my_list2]

In [44]:
my_array2 = np.array(my_lists)

In [45]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [46]:
my_array2.shape

(2, 4)

In [47]:
# Check the data type

In [48]:
my_array2.dtype

dtype('int32')

In [49]:
# special case arrays. array of zeros

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
my_zeros_array = np.zeros(5)

In [52]:
my_zeros_array.dtype

dtype('float64')

In [53]:
# An array of ones in a 5 x 5 dimension

In [54]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# identity matrix or array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# return evenly spaced values within a given interval
np.arange(5)

array([0, 1, 2, 3, 4])

In [57]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# USING ARRAYS AND SCALARS

In [59]:
arr1 = np.array([[1,2,3,4], [6,9,10,11]])

In [60]:
arr1

array([[ 1,  2,  3,  4],
       [ 6,  9, 10, 11]])

In [62]:
# multiple the value of the array with themselves
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 36,  81, 100, 121]])

In [63]:
# subtraction
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
# arithemetic operations
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.16666667, 0.11111111, 0.1       , 0.09090909]])

In [66]:
# exponential operation
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 216,  729, 1000, 1331]], dtype=int32)

#  INDEXING ARRAY

In [68]:
arr = np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr[3]

3

In [71]:
arr[1:5]

array([1, 2, 3, 4])

In [73]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [74]:
arr[0:5] = 100

In [75]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [76]:
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [80]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [81]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
# get a copy of the array to work with
arr_copy = arr.copy()

In [83]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
# indexing in a 2D array
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[1]

array([20, 25, 30])

In [86]:
arr_2d[1][0]

20

In [87]:
# slicing the array
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [91]:
# fancy indexing
arr2d = np.zeros((10,10))

In [92]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
arr_length = arr2d.shape[1]

In [94]:
arr_length

10

In [99]:
for i in range(arr_length):
    arr2d[i]=1

In [98]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])