# CREATING ARRAYS

In [14]:
import numpy as np

In [15]:
my_list1 = [1,2,3,4]

In [16]:
my_array1 = np.array(my_list1)

In [17]:
my_array1

array([1, 2, 3, 4])

In [18]:
my_list2 = [11,22,33,44]

In [19]:
my_lists = [my_list1, my_list2]

In [20]:
my_array2 = np.array(my_lists)

In [21]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [22]:
my_array2.shape

(2, 4)

In [23]:
# Check the data type

In [24]:
my_array2.dtype

dtype('int32')

In [25]:
# special case arrays. array of zeros

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
my_zeros_array = np.zeros(5)

In [28]:
my_zeros_array.dtype

dtype('float64')

In [29]:
# An array of ones in a 5 x 5 dimension

In [30]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# identity matrix or array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# return evenly spaced values within a given interval
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# USING ARRAYS AND SCALARS

In [34]:
arr1 = np.array([[1,2,3,4], [6,9,10,11]])

In [35]:
arr1

array([[ 1,  2,  3,  4],
       [ 6,  9, 10, 11]])

In [36]:
# multiple the value of the array with themselves
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 36,  81, 100, 121]])

In [37]:
# subtraction
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
# arithemetic operations
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.16666667, 0.11111111, 0.1       , 0.09090909]])

In [39]:
# exponential operation
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 216,  729, 1000, 1331]], dtype=int32)

#  INDEXING ARRAY

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[3]

3

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
# get a copy of the array to work with
arr_copy = arr.copy()

In [53]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
# indexing in a 2D array
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d[1]

array([20, 25, 30])

In [56]:
arr_2d[1][0]

20

In [57]:
# slicing the array
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
# fancy indexing
arr2d = np.zeros((10,10))

In [59]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
arr_length = arr2d.shape[1]

In [61]:
arr_length

10

In [62]:
for i in range(arr_length):
    arr2d[i]=i

In [63]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [64]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

#  ARRAY TRANSPOSITION

In [65]:
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [66]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [67]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [68]:
arr3d = np.arange(50).reshape((5,5,2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [69]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [70]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [71]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

#  UNIVERSAL ARRAY FUNCTIONS

In [72]:
uarr = np.arange(11)
uarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
np.sqrt(uarr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [74]:
np.exp(uarr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [75]:
A = np.random.randn(10)
A

array([-1.96561023,  1.34400158, -0.07966059,  1.62290782,  2.02709522,
        0.78575833, -0.28683702,  0.14204872,  0.29251154, -0.96661524])

In [76]:
B = np.random.randn(10)
B

array([ 0.53839578,  0.17409579, -0.03706174,  0.6331668 ,  0.05015376,
       -1.72779593,  0.19087547, -1.14000418, -1.61666567,  1.27202792])

In [77]:
# Binary function
np.add(A,B)

array([-1.42721445,  1.51809737, -0.11672233,  2.25607462,  2.07724898,
       -0.94203761, -0.09596155, -0.99795546, -1.32415413,  0.30541267])

In [78]:
# Max and Min between arrays
np.maximum(A,B)

array([ 0.53839578,  1.34400158, -0.03706174,  1.62290782,  2.02709522,
        0.78575833,  0.19087547,  0.14204872,  0.29251154,  1.27202792])

In [79]:
np.minimum(A,B)

array([-1.96561023,  0.17409579, -0.07966059,  0.6331668 ,  0.05015376,
       -1.72779593, -0.28683702, -1.14000418, -1.61666567, -0.96661524])

In [80]:
# documentation link below
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True