# CREATING ARRAYS

In [38]:
import numpy as np

In [39]:
my_list1 = [1,2,3,4]

In [40]:
my_array1 = np.array(my_list1)

In [41]:
my_array1

array([1, 2, 3, 4])

In [42]:
my_list2 = [11,22,33,44]

In [43]:
my_lists = [my_list1, my_list2]

In [44]:
my_array2 = np.array(my_lists)

In [45]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [46]:
my_array2.shape

(2, 4)

In [47]:
# Check the data type

In [48]:
my_array2.dtype

dtype('int32')

In [49]:
# special case arrays. array of zeros

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
my_zeros_array = np.zeros(5)

In [52]:
my_zeros_array.dtype

dtype('float64')

In [53]:
# An array of ones in a 5 x 5 dimension

In [54]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# identity matrix or array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# return evenly spaced values within a given interval
np.arange(5)

array([0, 1, 2, 3, 4])

In [57]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# USING ARRAYS AND SCALARS

In [59]:
arr1 = np.array([[1,2,3,4], [6,9,10,11]])

In [60]:
arr1

array([[ 1,  2,  3,  4],
       [ 6,  9, 10, 11]])

In [62]:
# multiple the value of the array with themselves
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 36,  81, 100, 121]])

In [63]:
# subtraction
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
# arithemetic operations
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.16666667, 0.11111111, 0.1       , 0.09090909]])