In [1]:
import numpy as np

In [4]:
my_list1 = [1,2,3,4]

In [5]:
my_array1 = np.array(my_list1)

In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]

In [10]:
my_lists = [my_list1, my_list2]

In [11]:
my_array2 = np.array(my_lists)

In [12]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [15]:
my_array2.shape

(2, 4)

In [16]:
# Check the data type

In [17]:
my_array2.dtype

dtype('int32')

In [18]:
# special case arrays. array of zeros

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
my_zeros_array = np.zeros(5)

In [21]:
my_zeros_array.dtype

dtype('float64')

In [22]:
# An array of ones in a 5 x 5 dimension

In [23]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# identity matrix or array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# return evenly spaced values within a given interval
np.arange(5)

array([0, 1, 2, 3, 4])